### PR TITLE
Removed separate proto compile step

### PR DESCRIPTION
**Pull request by haridas**
setup.py file does the necessary setups and configurations.

### CODE REVIEW

**Comment by junjuew** [comment]
Hello Haridas,

Thank you for taking the initiative to help improve this repo! Appreciate your efforts.

I fully agree that compiling the proto files automatically during package installation makes it easier to pull upstream changes and remove the needs of the manual compilation. 

One caveat with this current implementation is the introduction of "protoc" as an out-of-channel dependency. Users need to somehow make sure the right version of protoc is properly installed. As a thin wrapper aiming to install TF object detection with a simple `pip install`, is there a way we could remove the assumption of protoc availability in this PR?

Two approaches come to my mind to make this work:
Option 1. Package and publish protoc binary as a separate PyPI package. tf_object_detection would then specify that package as a dependency. (Maybe someone else has already done this)
Option 2. Download protoc binary during installation. Use the downloaded protoc binary to compile protobuf instead of assuming the existence of protoc.

**Comment by haridas** [comment]
Thanks @junjuew 

I was thinking in this line only, my take on these scenarios are, 

**Option 1:**

This is the normal flow expected, users just download and use the library from PyPI server using `pip install object_detection_tf`. The library author can publish any future updates to the PyPI server, by ensuring locally things are good.

**Option 2:**

This Is for those who download the source repo and play with it or customise and install under their environment using `python setup.py install`, I guess in that case giving user the flexibility to supply the `protoc` binary is right option. Having the clear Readme helps to avoid the version and other issues. We could do the download and handling of protoc but I feel as a library standpoint we can keep the external dependency as external.

**Comment by junjuew** [comment]
I see. Sounds good. Could you publish the package to the test PyPI server and send me the link? I'll merge the PR once I confirm the published wheel can be successfully installed through pip.

**Comment by haridas** [comment]
Sure, will update you once the test PyPI package ready.

**Comment by haridas** [comment]
Please try the pip package from this test server, 

```bash
pip install -i https://test.pypi.org/simple/ tf-object-detection==0.0.3
```

**Comment by junjuew** [comment]
LGTM

**Comment by haridas** [comment]
Thanks @junjuew

**Pull request merged**
